### ISSUE TITLE
Panic when rustfmt encounters a lambda with only `{}` inside

### ISSUE THREAD

**Issue by koute** [rust-lang/rustfmt#3874]
Consider the following code:

```rust
fn main() {
    || {{}};
}
```

`rustfmt` currently cannot format this and panics with the following:

```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /rustc/ed8b708c1a6bf6d94f860eeb6a6b0b442c380d7f/src/libcore/slice/mod.rs:2715:10
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:76
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:60
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1030
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:64
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:196
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:473
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:380
  12: rust_begin_unwind
             at src/libstd/panicking.rs:307
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  14: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:61
  15: rustfmt_nightly::closures::get_inner_expr
  16: rustfmt_nightly::closures::get_inner_expr
  17: rustfmt_nightly::closures::rewrite_closure
  18: rustfmt_nightly::expr::format_expr
  19: rustfmt_nightly::stmt::format_stmt
  20: rustfmt_nightly::visitor::FmtVisitor::walk_stmts
  21: rustfmt_nightly::visitor::FmtVisitor::visit_block
  22: rustfmt_nightly::visitor::FmtVisitor::visit_fn
  23: rustfmt_nightly::visitor::FmtVisitor::visit_item
  24: rustfmt_nightly::reorder::<impl rustfmt_nightly::visitor::FmtVisitor>::visit_items_with_reordering
  25: rustfmt_nightly::visitor::FmtVisitor::walk_mod_items
  26: rustfmt_nightly::visitor::FmtVisitor::format_separate_mod
  27: rustfmt_nightly::formatting::format_project
  28: syntax::with_globals
  29: rustfmt_nightly::Session<T>::format
  30: rustfmt::format_and_emit_report
  31: rustfmt::execute
  32: rustfmt::main
  33: std::rt::lang_start::{{closure}}
  34: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  35: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  36: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  37: std::panicking::try
             at src/libstd/panicking.rs:271
  38: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  39: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  40: main
  41: __libc_start_main
  42: <unknown>
```

[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0b3da141312bbeda24a9fd00bf87f4ad)

Affected versions:
rustfmt 1.4.8-nightly (afb1ee1 2019-09-08)
rustfmt 1.4.9-nightly (33e3667 2019-10-07)

**Comment by topecongiro** [comment]
Closing as a dup of #3844. Thanks!
