### ISSUE TITLE
fails with conditional paths that include -

### ISSUE THREAD

**Issue by bmc-msft** [rust-lang/rustfmt#3933]
I have minimized a reproduction, but it requires multiple files.  From my testing, renaming imp-a.rs and imp-b.rs to use underscore rather than dash works.

src/lib.rs
```
#[cfg_attr(windows, path = "imp-a.rs")]
#[cfg_attr(not(windows), path = "imp-b.rs")]
mod imp;
pub use imp::A;
```

src/imp-a.rs
```
mod utils;
pub struct A;
```

src/imp-b.rs
```
pub struct A;
```

src/utils.rs
```
// this can have any valid rust in it, or can be empty.  but it must exist.
```

This happens on both stable & nightly.
```
$ cargo fmt --version
rustfmt 1.4.8-stable (afb1ee1 2019-09-08)
$ RUST_BACKTRACE=full cargo fmt
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
stack backtrace:
   0:     0x56240d417e34 - backtrace::backtrace::libunwind::trace::hda41dbcdfba36aa0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1:     0x56240d417e34 - backtrace::backtrace::trace_unsynchronized::h1a8d6e1f8cb3f5d4
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2:     0x56240d417e34 - std::sys_common::backtrace::_print_fmt::h610c4127487e10da
                               at src/libstd/sys_common/backtrace.rs:76
   3:     0x56240d417e34 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0722dc552e01bd1d
                               at src/libstd/sys_common/backtrace.rs:60
   4:     0x56240d4390ac - core::fmt::write::h01edf6dd68a42c9c
                               at src/libcore/fmt/mod.rs:1030
   5:     0x56240d414db7 - std::io::Write::write_fmt::hf15985f193f03c04
                               at src/libstd/io/mod.rs:1412
   6:     0x56240d41a245 - std::sys_common::backtrace::_print::hd8d5d08a1795e743
                               at src/libstd/sys_common/backtrace.rs:64
   7:     0x56240d41a245 - std::sys_common::backtrace::print::hf89a79e3921a2366
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x56240d41a245 - std::panicking::default_hook::{{closure}}::h3a8f42beb3bb8ae3
                               at src/libstd/panicking.rs:196
   9:     0x56240d419f36 - std::panicking::default_hook::h8f803b0bc31a5c37
                               at src/libstd/panicking.rs:210
  10:     0x56240d41a945 - std::panicking::rust_panic_with_hook::h825f041245da8739
                               at src/libstd/panicking.rs:473
  11:     0x56240d41a4e2 - std::panicking::continue_panic_fmt::hbe0378e33481e81b
                               at src/libstd/panicking.rs:380
  12:     0x56240d41a3d6 - rust_begin_unwind
                               at src/libstd/panicking.rs:307
  13:     0x56240d43498a - core::panicking::panic_fmt::h527855ce0bc891f6
                               at src/libcore/panicking.rs:85
  14:     0x56240d4348c9 - core::panicking::panic::h2f49f09cf859b728
                               at src/libcore/panicking.rs:49
  15:     0x56240d1b0a19 - rustfmt_nightly::attr::<impl rustfmt_nightly::rewrite::Rewrite for syntax::ast::Attribute>::rewrite::ha11157b76afa715b
  16:     0x56240d1b0eb0 - rustfmt_nightly::attr::<impl rustfmt_nightly::rewrite::Rewrite for [syntax::ast::Attribute]>::rewrite::h549f328f56a6a721
  17:     0x56240d0ca1dd - rustfmt_nightly::items::rewrite_attrs::h0039976451e34c06
  18:     0x56240d0ca7aa - rustfmt_nightly::items::rewrite_mod::h6868ac9144f45c60
  19:     0x56240d0fbecc - <rustfmt_nightly::lists::ListItems<I,F1,F2,F3> as core::iter::traits::iterator::Iterator>::next::h33b964bee908a420
  20:     0x56240d114719 - <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter::h60cf19b6c436fa5a
  21:     0x56240d131bf8 - rustfmt_nightly::reorder::<impl rustfmt_nightly::visitor::FmtVisitor>::visit_items_with_reordering::h6db3d04454e98a46
  22:     0x56240d13ea4f - rustfmt_nightly::visitor::FmtVisitor::walk_mod_items::h419ace8ee43d8746
  23:     0x56240d13f3a6 - rustfmt_nightly::visitor::FmtVisitor::format_separate_mod::h7955263c2d650d8f
  24:     0x56240d065e27 - rustfmt_nightly::formatting::format_project::hbfeaa7d6896f9d79
  25:     0x56240d050be0 - syntax::with_globals::hccee834bfe708c7e
  26:     0x56240d05119e - rustfmt_nightly::Session<T>::format::hf1a3ebcff1ff224d
  27:     0x56240d06294b - rustfmt::format_and_emit_report::hb19cde19e24b77a1
  28:     0x56240d05fca0 - rustfmt::execute::h52cb5f888f8121be
  29:     0x56240d05c15c - rustfmt::main::h77061d0691c09b64
  30:     0x56240d054a33 - std::rt::lang_start::{{closure}}::h139a2fa5de864e54
  31:     0x56240d41a373 - std::rt::lang_start_internal::{{closure}}::ha04574f12d97cbe2
                               at src/libstd/rt.rs:49
  32:     0x56240d41a373 - std::panicking::try::do_call::h7c2a8488f72db90c
                               at src/libstd/panicking.rs:292
  33:     0x56240d41cd8a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  34:     0x56240d41aefd - std::panicking::try::hc3a9b5da4250385d
                               at src/libstd/panicking.rs:271
  35:     0x56240d41aefd - std::panic::catch_unwind::hf27600bf8c37809a
                               at src/libstd/panic.rs:394
  36:     0x56240d41aefd - std::rt::lang_start_internal::h409d4f2fe51133b0
                               at src/libstd/rt.rs:48
  37:     0x56240d0637c2 - main
  38:     0x7f688e24cb97 - __libc_start_main
  39:     0x56240d044b29 - <unknown>
$ cargo +nightly fmt --version
rustfmt 1.4.9-nightly (33e3667 2019-10-07)
$ RUST_BACKTRACE=full cargo +nightly fmt
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/5c5b8afd80e6fa1d24632153cb2257c686041d41/src/libcore/macros.rs:17:40
stack backtrace:
   0:     0x556960f1e614 - backtrace::backtrace::libunwind::trace::h03a3268e8025f5e7
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x556960f1e614 - backtrace::backtrace::trace_unsynchronized::hfdd426654407b9b1
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x556960f1e614 - std::sys_common::backtrace::_print_fmt::hf13b3576a7afd1fd
                               at src/libstd/sys_common/backtrace.rs:84
   3:     0x556960f1e614 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6120b5cb7f3f6fb4
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x556960f3f66c - core::fmt::write::h5519681e0b8a2078
                               at src/libcore/fmt/mod.rs:1030
   5:     0x556960f1b727 - std::io::Write::write_fmt::h244d0a52d18abc18
                               at src/libstd/io/mod.rs:1412
   6:     0x556960f2068e - std::sys_common::backtrace::_print::h3f6ea6d8a2e1ae5c
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x556960f2068e - std::sys_common::backtrace::print::hfaa195f2a5ad8cee
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x556960f2068e - std::panicking::default_hook::{{closure}}::heac2a010ba47da52
                               at src/libstd/panicking.rs:188
   9:     0x556960f20381 - std::panicking::default_hook::h7739a4bc79ee19ed
                               at src/libstd/panicking.rs:205
  10:     0x556960f20d8b - std::panicking::rust_panic_with_hook::h4882a1e7ece8be98
                               at src/libstd/panicking.rs:464
  11:     0x556960f2092e - std::panicking::continue_panic_fmt::h14c4652068d7f110
                               at src/libstd/panicking.rs:373
  12:     0x556960f20816 - rust_begin_unwind
                               at src/libstd/panicking.rs:302
  13:     0x556960f3b0ae - core::panicking::panic_fmt::h15bba873f536c8cb
                               at src/libcore/panicking.rs:82
  14:     0x556960f3affa - core::panicking::panic::h9f2c59d2ef6ff75a
                               at src/libcore/panicking.rs:50
  15:     0x556960cca101 - rustfmt_nightly::attr::<impl rustfmt_nightly::rewrite::Rewrite for rustc_ap_syntax::ast::Attribute>::rewrite::h7d4571541a01fdce
  16:     0x556960cca600 - rustfmt_nightly::attr::<impl rustfmt_nightly::rewrite::Rewrite for [rustc_ap_syntax::ast::Attribute]>::rewrite::h22f8504379336f43
  17:     0x556960befadb - rustfmt_nightly::items::rewrite_attrs::h5275ddb78c2780f9
  18:     0x556960bf010a - rustfmt_nightly::items::rewrite_mod::h4638057ca0f5df90
  19:     0x556960c3e9bc - <rustfmt_nightly::lists::ListItems<I,F1,F2,F3> as core::iter::traits::iterator::Iterator>::next::hb881a45806cfdbaf
  20:     0x556960c29359 - <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter::h86542a17d1ed16be
  21:     0x556960c77190 - rustfmt_nightly::reorder::rewrite_reorderable_items::h903afd769ecae241
  22:     0x556960c471a5 - rustfmt_nightly::reorder::<impl rustfmt_nightly::visitor::FmtVisitor>::visit_items_with_reordering::ha49cd466aeb6a2d6
  23:     0x556960c52b8f - rustfmt_nightly::visitor::FmtVisitor::walk_mod_items::h2f3e41f9c09f5a4f
  24:     0x556960c53576 - rustfmt_nightly::visitor::FmtVisitor::format_separate_mod::h6c88b025c92f888f
  25:     0x556960b7f07b - rustfmt_nightly::formatting::format_project::h01f983835aca3c84
  26:     0x556960b62346 - scoped_tls::ScopedKey<T>::set::h066863dc286efc5b
  27:     0x556960b86ee6 - rustc_ap_syntax::with_globals::h4ff35e2f5a8c788c
  28:     0x556960b69b2e - rustfmt_nightly::Session<T>::format::h0cdc6d940be2699b
  29:     0x556960b7d18b - rustfmt::format_and_emit_report::heb56d82e771748b4
  30:     0x556960b7a5d0 - rustfmt::execute::h844f8c4cc8a036de
  31:     0x556960b76804 - rustfmt::main::hc47a56c7e111b592
  32:     0x556960b85723 - std::rt::lang_start::{{closure}}::hca878fbb4132e5ad
  33:     0x556960f207b3 - std::rt::lang_start_internal::{{closure}}::hc2740ed8935d2053
                               at src/libstd/rt.rs:48
  34:     0x556960f207b3 - std::panicking::try::do_call::h3894402739883b06
                               at src/libstd/panicking.rs:287
  35:     0x556960f233da - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  36:     0x556960f2132d - std::panicking::try::h5db65b65b7947775
                               at src/libstd/panicking.rs:265
  37:     0x556960f2132d - std::panic::catch_unwind::hf99e4cf1cf67ce18
                               at src/libstd/panic.rs:395
  38:     0x556960f2132d - std::rt::lang_start_internal::h08e212477f161066
                               at src/libstd/rt.rs:47
  39:     0x556960b7de92 - main
  40:     0x7f02495eab97 - __libc_start_main
  41:     0x556960b5e529 - <unknown>
$
```

**Comment by rchaser53** [comment]
This bug seems to be caused by rustfmt parsing only one module.
rustfmt parses only either one(imp-a.rs or imp-b.rs), so doesn't have both spans.
But rustfmt tries to format both files and fails to emit the snippet.

**Comment by rchaser53** [comment]
This is not correct, Maybe this is caused the attribute path 'warn_directory_ownership'.
This attribute span hi and lo is always 0 and it's not a correct value.
https://github.com/rust-lang/rustfmt/issues/3933#issuecomment-556071219
