### ISSUE TITLE
cargo fmt panics

### ISSUE THREAD

**Issue by Hirrolot** [rust-lang/rustfmt#3986]
```
$ RUST_BACKTRACE=full cargo fmt
thread 'main' panicked at 'begin <= end (12 <= 11) when slicing `fn main() {}
`', src/libcore/str/mod.rs:2056:5
stack backtrace:
   0:     0x556310a087c4 - backtrace::backtrace::libunwind::trace::h257ee8fa702033a5
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x556310a087c4 - backtrace::backtrace::trace_unsynchronized::h5f0627dd9ccaab6f
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x556310a087c4 - std::sys_common::backtrace::_print_fmt::h4ed17834c4e5b6fe
                               at src/libstd/sys_common/backtrace.rs:84
   3:     0x556310a087c4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h68dbadc0bcc77b5f
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x556310a2950c - core::fmt::write::hc38fdda30204d4dc
                               at src/libcore/fmt/mod.rs:1025
   5:     0x556310a058b7 - std::io::Write::write_fmt::h0900d6e763137782
                               at src/libstd/io/mod.rs:1426
   6:     0x556310a0a83e - std::sys_common::backtrace::_print::h03ca3de8c1fabc8b
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x556310a0a83e - std::sys_common::backtrace::print::h0089c2a21e41632b
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x556310a0a83e - std::panicking::default_hook::{{closure}}::he2d2ff837d4de97e
                               at src/libstd/panicking.rs:193
   9:     0x556310a0a531 - std::panicking::default_hook::h2f717321fdee40b4
                               at src/libstd/panicking.rs:210
  10:     0x556310a0af1b - std::panicking::rust_panic_with_hook::h9d80a6967ad27edd
                               at src/libstd/panicking.rs:471
  11:     0x556310a0aace - rust_begin_unwind
                               at src/libstd/panicking.rs:375
  12:     0x556310a24f4e - core::panicking::panic_fmt::h15ac915805b55762
                               at src/libcore/panicking.rs:84
  13:     0x556310a26794 - core::str::slice_error_fail::h758dc7b56e07189f
                               at src/libcore/str/mod.rs:0
  14:     0x556310749b82 - core::str::traits::<impl core::slice::SliceIndex<str> for core::ops::range::Range<usize>>::index::{{closure}}::h498c9d9815b95bf2
  15:     0x5563107627c6 - rustfmt_nightly::format_code_block::h41baf8d7ac5ebe47
  16:     0x5563107baf77 - rustfmt_nightly::comment::rewrite_comment_inner::hbf16323955f2cbc6
  17:     0x5563107b769b - rustfmt_nightly::comment::identify_comment::hca36d652c9cec9bb
  18:     0x5563106c64a2 - rustfmt_nightly::missed_spans::<impl rustfmt_nightly::visitor::FmtVisitor>::process_comment::h05da26d0323317c4
  19:     0x5563106c5488 - rustfmt_nightly::missed_spans::<impl rustfmt_nightly::visitor::FmtVisitor>::format_missing_with_indent::h6f35fe6527f5a58d
  20:     0x5563106d141f - rustfmt_nightly::visitor::FmtVisitor::push_rewrite::h0b017fe566158755
  21:     0x5563106c7666 - rustfmt_nightly::reorder::<impl rustfmt_nightly::visitor::FmtVisitor>::visit_items_with_reordering::ha31f4ce9369ce10a
  22:     0x5563106d2896 - rustfmt_nightly::visitor::FmtVisitor::walk_mod_items::h9f449f3d0d6dc75d
  23:     0x5563106d3266 - rustfmt_nightly::visitor::FmtVisitor::format_separate_mod::h9b9545af1afd68c7
  24:     0x5563106530db - rustfmt_nightly::formatting::format_project::hef3ef24f282b33c5
  25:     0x55631065b2f9 - rustc_ap_syntax::with_globals::h5f423a1ba32882b8
  26:     0x55631063bade - rustfmt_nightly::Session<T>::format::he1931ff9b290247f
  27:     0x5563106511fb - rustfmt::format_and_emit_report::h896db598129c02c3
  28:     0x55631064e2e0 - rustfmt::execute::h0ecf4f26ea5d75d8
  29:     0x55631064a6e4 - rustfmt::main::h504ad92205336b38
  30:     0x55631063e683 - std::rt::lang_start::{{closure}}::heac2f5df62bbc190
  31:     0x556310a0a963 - std::rt::lang_start_internal::{{closure}}::hc3a7bf6141d6fb71
                               at src/libstd/rt.rs:52
  32:     0x556310a0a963 - std::panicking::try::do_call::h1f3e9b1e5088796f
                               at src/libstd/panicking.rs:292
  33:     0x556310a0d55a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  34:     0x556310a0b470 - std::panicking::try::h9241957305334fb5
                               at src/libstd/panicking.rs:270
  35:     0x556310a0b470 - std::panic::catch_unwind::h6f26ed7457a3b67e
                               at src/libstd/panic.rs:394
  36:     0x556310a0b470 - std::rt::lang_start_internal::hf225ee90fc1b21bb
                               at src/libstd/rt.rs:51
  37:     0x556310651f82 - main
  38:     0x7f5d60227b97 - __libc_start_main
  39:     0x556310632929 - <unknown>
```

## My version
```
nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.42.0-nightly (0de96d37f 2019-12-19)
```

## My system
```
                                       hirrolot@hirrolot-desktop
 MMMMMMMMMMMMMMMMMMMMMMMMMmds+.        OS: Mint 19.1 tessa
 MMm----::-://////////////oymNMd+`     Kernel: x86_64 Linux 4.15.0-20-generic
 MMd      /++                -sNMd:    Uptime: 4h 9m
 MMNso/`  dMM    `.::-. .-::.` .hMN:   Packages: 2221
 ddddMMh  dMM   :hNMNMNhNMNMNh: `NMm   Shell: bash 4.4.20
     NMm  dMM  .NMN/-+MMM+-/NMN` dMM   Resolution: 1920x1080
     NMm  dMM  -MMm  `MMM   dMM. dMM   DE: Cinnamon 4.0.10
     NMm  dMM  -MMm  `MMM   dMM. dMM   WM: Muffin
     NMm  dMM  .mmd  `mmm   yMM. dMM   WM Theme: Mint-Y-Dark (Mint-Y)
     NMm  dMM`  ..`   ...   ydm. dMM   GTK Theme: Mint-Y [GTK2/3]
     hMM- +MMd/-------...-:sdds  dMM   Icon Theme: Mint-Y
     -NMm- :hNMNNNmdddddddddy/`  dMM   Font: Noto Sans 9
      -dMNs-``-::::-------.``    dMM   CPU: Intel Core i7-6700 @ 8x 4GHz [40.5°C]
       `/dMNmy+/:-------------:/yMMM   GPU: GeForce GTX 1060 6GB
          ./ydNMMMMMMMMMMMMMMMMMMMMM   RAM: 2887MiB / 7927MiB
             \.MMMMMMMMMMMMMMMMMMM    
```

**Comment by calebcartwright** [comment]
hi @Hirrolot, could you please also include a snippet of the code you were running `cargo fmt` against?

**Comment by Hirrolot** [comment]
Hi, @calebcartwright. Unfortunately, when I tried to rewrite the code the playground, rustfmt didn't panic. The code was very long.

**Comment by calebcartwright** [comment]
That's going to make it rather difficult to debug 🤔 Could you try running `rustfmt` directly against individual files to narrow down where the problem may be?

For example:
```bash
$ rustfmt src/lib.rs --verbose --check --edition 2018 --skip-children --unstable-features
```

Also, do you have a rustfmt config file with any configuration options set, and/or are you providing any additional options/args when you are running `cargo fmt`?

**Comment by Hirrolot** [comment]
> Also, do you have a rustfmt config file with any configuration options set, and/or are you providing any additional options/args when you are running cargo fmt?

Yes, with `format_code_in_doc_comments = true` rustfmt panicked, but with `format_code_in_doc_comments = false` it didn't.

**Comment by Hirrolot** [comment]
> Could you try running rustfmt directly against individual files to narrow down where the problem may be?

Ok, I'll try.

**Comment by calebcartwright** [comment]
> Yes, with format_code_in_doc_comments = true rustfmt panicked, but with format_code_in_doc_comments = false it didn't.

Thanks that definitely helps!

You could also try `cargo fmt --verbose` to see if that surfaces up the problematic file too

**Comment by Hirrolot** [comment]
@calebcartwright, sorry, I tried to recover the problematic file, but unsuccessfully. That's all I have.

**Comment by calebcartwright** [comment]
Obviously the panic is undesireable, but without any code/repo/references/etc. I'm not sure anything can be done on the rustfmt side
