### ISSUE TITLE
thread 'main' panicked at 'component rustfmt should be in the manifest', src/toolchain.rs:358:33

### ISSUE THREAD

**Issue by raphaelsoul** [rust-lang/rustfmt#4892]
got error when running `cargo format`

original full trace:
```
$ RUST_BACKTRACE=full cargo fmt      
thread 'main' panicked at 'component rustfmt should be in the manifest', src/toolchain.rs:358:33
stack backtrace:
   0:        0x101b1c6a3 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h80b40bec9b25cdb7
   1:        0x10177765e - core::fmt::write::h367e10cc391177e1
   2:        0x101b1bfd6 - std::io::Write::write_fmt::h69f760cf0ceceb64
   3:        0x101b1b9c9 - std::panicking::default_hook::{{closure}}::h6b461dbc832ae479
   4:        0x101b1af06 - std::panicking::default_hook::hf6b37b6d4ff1b717
   5:        0x101b1aae5 - std::panicking::rust_panic_with_hook::hcc0074a2cdf70335
   6:        0x101b3cafa - std::panicking::begin_panic_handler::{{closure}}::hafebb92bbb4f046c
   7:        0x101b3ca68 - std::sys_common::backtrace::__rust_end_short_backtrace::hbd3b6a5769847c0d
   8:        0x101b3ca10 - _rust_begin_unwind
   9:        0x101c494bf - std::panicking::begin_panic_fmt::h7722ff9c8a9c34c7
  10:        0x101aacc92 - rustup::toolchain::InstalledCommonToolchain::create_command::{{closure}}::h35c45cbd1e9914c5
  11:        0x101aac9bb - rustup::toolchain::InstalledCommonToolchain::create_command::hb7a6621eba0964d1
  12:        0x10170c7fe - rustup_init::main::hd7de224a8198caa6
  13:        0x10170758a - std::sys_common::backtrace::__rust_begin_short_backtrace::hf1d3a9658641fc2a
  14:        0x10170e2f4 - _main
```

env info:
```
$ rustup show
Default host: x86_64-apple-darwin
rustup home:  /Users/raphaelsoul/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
nightly-x86_64-apple-darwin

active toolchain
----------------

stable-x86_64-apple-darwin (directory override for '/Users/raphaelsoul/projects/github.com/raphaelsoul/rustblog')
rustc 1.53.0 (53cb7b09b 2021-06-17)
```

Cargo.toml
```
[workspace]
members=["guess", "http", "video"]
```

```
$ rustup component list | grep x86_64-apple-darwin
cargo-x86_64-apple-darwin (installed)
clippy-preview-x86_64-apple-darwin
llvm-tools-preview-x86_64-apple-darwin
rls-preview-x86_64-apple-darwin
rust-analysis-x86_64-apple-darwin
rust-docs-x86_64-apple-darwin (installed)
rust-std-x86_64-apple-darwin (installed)
rustc-x86_64-apple-darwin (installed)
rustc-dev-x86_64-apple-darwin
rustfmt-preview-x86_64-apple-darwin
```

rustfmt not installed but i have it in executable binaries home
```
$ ls -al ~/.cargo/bin                             
total 225672
drwxr-xr-x  15 raphaelsoul  staff      480 Jul  6 15:35 .
drwxr-xr-x  10 raphaelsoul  staff      320 Jul  6 15:01 ..
-rwxr-xr-x  12 raphaelsoul  staff  9500104 Jun 28 11:11 cargo
-rwxr-xr-x  12 raphaelsoul  staff  9500104 Jun 28 11:11 cargo-clippy
-rwxr-xr-x  12 raphaelsoul  staff  9500104 Jun 28 11:11 cargo-fmt
-rwxr-xr-x  12 raphaelsoul  staff  9500104 Jun 28 11:11 cargo-miri
-rwxr-xr-x  12 raphaelsoul  staff  9500104 Jun 28 11:11 clippy-driver
-rwxr-xr-x  12 raphaelsoul  staff  9500104 Jun 28 11:11 rls
-rwxr-xr-x  12 raphaelsoul  staff  9500104 Jun 28 11:11 rust-gdb
-rwxr-xr-x  12 raphaelsoul  staff  9500104 Jun 28 11:11 rust-lldb
-rwxr-xr-x  12 raphaelsoul  staff  9500104 Jun 28 11:11 rustc
-rwxr-xr-x  12 raphaelsoul  staff  9500104 Jun 28 11:11 rustdoc
-rwxr-xr-x  12 raphaelsoul  staff  9500104 Jun 28 11:11 rustfmt
-rwxr-xr-x  12 raphaelsoul  staff  9500104 Jun 28 11:11 rustup
-rwxr-xr-x   1 raphaelsoul  staff   921560 Nov  7  2018 wasm-gc
```

Any ideas on what happening and how to solve it?

**Comment by calebcartwright** [comment]
Thanks for the report but the panic seems to be coming out of rustup. Could you please report the issue to the rustup team in https://github.com/rust-lang/rustup?

heads up on an incoming @kinnison, feel free to loop me back in if there ends up being a rustfmt wrinkle to this
