### ISSUE TITLE
no errors encountered even though `delay_span_bug` issued

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/rustfmt#5192]
Reproducible at [teloxide-core#828ab071](https://github.com/teloxide/teloxide-core/tree/828ab071621f99273676771eae08c2984f4ed2ed).
```
; cargo +nightly-2022-01-24 fmt
thread 'main' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:1188:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

<details><summary>Backtrace</summary>
<p>

```
; cargo +nightly-2022-01-24 fmt
thread 'main' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:1188:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84322efad553c7a79c80189f2d1b9197c1aa005f/library/std/src/panicking.rs:577:5
   1: core::panicking::panic_fmt
             at /rustc/84322efad553c7a79c80189f2d1b9197c1aa005f/library/core/src/panicking.rs:135:14
   2: core::panicking::panic_display::<&str>
   3: <rustc_errors::HandlerInner>::flush_delayed
   4: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
   5: <rustfmt_nightly::parse::session::ParseSess>::set_silent_emitter
   6: rustfmt_nightly::formatting::format_project::<rustfmt_nightly::Session<alloc::vec::Vec<u8>>>
   7: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::with::<<rustfmt_nightly::Session<alloc::vec::Vec<u8>>>::format_input_inner::{closure#0}, core::result::Result<rustfmt_nightly::FormatReport, rustfmt_nightly::ErrorKind>>
   8: <rustfmt_nightly::Session<alloc::vec::Vec<u8>>>::format_input_inner
   9: std::panicking::try::<core::option::Option<rustfmt_nightly::FormattedSnippet>, rustfmt_nightly::format_snippet::{closure#0}>
  10: rustfmt_nightly::format_snippet
  11: rustfmt_nightly::format_code_block
  12: <rustfmt_nightly::macros::MacroBranch>::rewrite
  13: <rustfmt_nightly::lists::ListItems<core::slice::iter::Iter<rustfmt_nightly::macros::MacroBranch>, rustfmt_nightly::macros::rewrite_macro_def::{closure#1}, rustfmt_nightly::macros::rewrite_macro_def::{closure#2}, rustfmt_nightly::macros::rewrite_macro_def::{closure#3}> as core::iter::traits::iterator::Iterator>::next
  14: <alloc::vec::Vec<rustfmt_nightly::lists::ListItem> as alloc::vec::spec_from_iter::SpecFromIter<rustfmt_nightly::lists::ListItem, rustfmt_nightly::lists::ListItems<core::slice::iter::Iter<rustfmt_nightly::macros::MacroBranch>, rustfmt_nightly::macros::rewrite_macro_def::{closure#1}, rustfmt_nightly::macros::rewrite_macro_def::{closure#2}, rustfmt_nightly::macros::rewrite_macro_def::{closure#3}>>>::from_iter
  15: rustfmt_nightly::macros::rewrite_macro_def
  16: <rustfmt_nightly::visitor::FmtVisitor>::visit_item
  17: <rustfmt_nightly::visitor::FmtVisitor>::visit_items_with_reordering
  18: <rustfmt_nightly::visitor::FmtVisitor>::format_separate_mod
  19: rustfmt_nightly::formatting::format_project::<rustfmt_nightly::Session<std::io::stdio::Stdout>>
  20: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::with::<<rustfmt_nightly::Session<std::io::stdio::Stdout>>::format_input_inner::{closure#0}, core::result::Result<rustfmt_nightly::FormatReport, rustfmt_nightly::ErrorKind>>
  21: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_span::create_session_if_not_set_then<core::result::Result<rustfmt_nightly::FormatReport, rustfmt_nightly::ErrorKind>, <rustfmt_nightly::Session<std::io::stdio::Stdout>>::format_input_inner::{closure#0}>::{closure#0}, core::result::Result<rustfmt_nightly::FormatReport, rustfmt_nightly::ErrorKind>>
  22: <rustfmt_nightly::Session<std::io::stdio::Stdout>>::format
  23: rustfmt::format_and_emit_report::<std::io::stdio::Stdout>
  24: <rustfmt_nightly::Session<std::io::stdio::Stdout>>::override_config::<rustfmt::format::{closure#0}, ()>
  25: rustfmt::execute
  26: rustfmt::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

**Comment by WaffleLapkin** [comment]
Seems to be introduced in `nightly-2022-01-18`:
```
; cargo +nightly-2022-01-17 fmt && echo "(just fine)"
(just fine)
; cargo +nightly-2022-01-18 fmt                      
thread 'main' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:1188:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by calebcartwright** [comment]
Thanks for the report! A compiler panic is probably best reported in rust-lang/rust, even though it's being surfaced by a dev tool. I'll check with infra to see if it makes sense to move the issue

We actually haven't made any changes to rustfmt in that window (https://github.com/rust-lang/rust/commits/master/src/tools/rustfmt) and the [minimal changes that were applied by folks working on the compiler](https://github.com/rust-lang/rust/commits/master/src/tools/rustfmt) were highly minimal and certainly don't strike me as anything that would be the root cause.

As such I suspect this is due to changes made elsewhere within the compiler mods, and would at least like for those folks to be aware (even if we need to make changes on the rustfmt side to address/work around)

Would you be up for trying to boil it down to a more simple repro case?
