### ISSUE TITLE
ICE: `panicked at 'Box<dyn Any>`

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rustfmt#5734]
````rust
fn fun<'tcx>() {
    assert!(matches!(&source.kind(), &ty::Dynamic(..)) && !source.needs_inferGenericParamDefKind::Lifetime => tcx.lifetimes.re_erased.into(),);
}


````
`rustfmt --check code.rs`

````
thread 'main' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1680:13
stack backtrace:
   0:     0x7f0f50d65f8a - std::backtrace_rs::backtrace::libunwind::trace::hc36a5d781c5b5ccc
                               at /rustc/3a8a131e9509c478ece1c58fe0ea2d49463d2300/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f0f50d65f8a - std::backtrace_rs::backtrace::trace_unsynchronized::hdf896053c14221b1
                               at /rustc/3a8a131e9509c478ece1c58fe0ea2d49463d2300/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f0f50d65f8a - std::sys_common::backtrace::_print_fmt::h39cabfaabdc86ac1
                               at /rustc/3a8a131e9509c478ece1c58fe0ea2d49463d2300/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f0f50d65f8a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h03d255761b970500
                               at /rustc/3a8a131e9509c478ece1c58fe0ea2d49463d2300/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f0f50dca05f - core::fmt::write::h9be633e4e0b71092
                               at /rustc/3a8a131e9509c478ece1c58fe0ea2d49463d2300/library/core/src/fmt/mod.rs:1254:17
   5:     0x7f0f50d58bc5 - std::io::Write::write_fmt::hf094eaeff4c6712a
                               at /rustc/3a8a131e9509c478ece1c58fe0ea2d49463d2300/library/std/src/io/mod.rs:1698:15
   6:     0x7f0f50d65d55 - std::sys_common::backtrace::_print::hb3526973e1a9ef48
                               at /rustc/3a8a131e9509c478ece1c58fe0ea2d49463d2300/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f0f50d65d55 - std::sys_common::backtrace::print::h8b0ebf35d627197b
                               at /rustc/3a8a131e9509c478ece1c58fe0ea2d49463d2300/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f0f50d689fe - std::panicking::default_hook::{{closure}}::h800b864dad9a2ddb
                               at /rustc/3a8a131e9509c478ece1c58fe0ea2d49463d2300/library/std/src/panicking.rs:269:22
   9:     0x7f0f50d687a5 - std::panicking::default_hook::h47199288a8f9de13
                               at /rustc/3a8a131e9509c478ece1c58fe0ea2d49463d2300/library/std/src/panicking.rs:288:9
  10:     0x7f0f50d6906e - std::panicking::rust_panic_with_hook::hb6edee1e00f0405f
                               at /rustc/3a8a131e9509c478ece1c58fe0ea2d49463d2300/library/std/src/panicking.rs:690:13
  11:     0x7f0f540951c1 - std[86a3120b066ce118]::panicking::begin_panic::<rustc_errors[392de8a05365fdc1]::DelayedBugPanic>::{closure#0}
  12:     0x7f0f54095116 - std[86a3120b066ce118]::sys_common::backtrace::__rust_end_short_backtrace::<std[86a3120b066ce118]::panicking::begin_panic<rustc_errors[392de8a05365fdc1]::DelayedBugPanic>::{closure#0}, !>
  13:     0x7f0f5409bdf6 - std[86a3120b066ce118]::panicking::begin_panic::<rustc_errors[392de8a05365fdc1]::DelayedBugPanic>
  14:     0x7f0f53593845 - <rustc_errors[392de8a05365fdc1]::HandlerInner>::flush_delayed::<alloc[4793a7dc0fb9f9dd]::vec::Vec<rustc_errors[392de8a05365fdc1]::DelayedDiagnostic>, &str>
  15:     0x7f0f53593022 - <rustc_errors[392de8a05365fdc1]::HandlerInner as core[c98013cfbe010fb2]::ops::drop::Drop>::drop
  16:     0x55e429ddf9e2 - core[c98013cfbe010fb2]::ptr::drop_in_place::<rustfmt_nightly[2b26fbdfc5662f3a]::parse::session::ParseSess>
  17:     0x55e429dde4fe - rustfmt_nightly[2b26fbdfc5662f3a]::formatting::format_project::<rustfmt_nightly[2b26fbdfc5662f3a]::Session<std[86a3120b066ce118]::io::stdio::Stdout>>
  18:     0x55e429ddc990 - <scoped_tls[32dd083a3f62f99a]::ScopedKey<rustc_span[ea3aeb57fd08449]::SessionGlobals>>::with::<<rustfmt_nightly[2b26fbdfc5662f3a]::Session<std[86a3120b066ce118]::io::stdio::Stdout>>::format_input_inner::{closure#0}, core[c98013cfbe010fb2]::result::Result<rustfmt_nightly[2b26fbdfc5662f3a]::FormatReport, rustfmt_nightly[2b26fbdfc5662f3a]::ErrorKind>>
  19:     0x55e429dd9a3f - <scoped_tls[32dd083a3f62f99a]::ScopedKey<rustc_span[ea3aeb57fd08449]::SessionGlobals>>::set::<rustc_span[ea3aeb57fd08449]::create_session_if_not_set_then<core[c98013cfbe010fb2]::result::Result<rustfmt_nightly[2b26fbdfc5662f3a]::FormatReport, rustfmt_nightly[2b26fbdfc5662f3a]::ErrorKind>, <rustfmt_nightly[2b26fbdfc5662f3a]::Session<std[86a3120b066ce118]::io::stdio::Stdout>>::format_input_inner::{closure#0}>::{closure#0}, core[c98013cfbe010fb2]::result::Result<rustfmt_nightly[2b26fbdfc5662f3a]::FormatReport, rustfmt_nightly[2b26fbdfc5662f3a]::ErrorKind>>
  20:     0x55e429e026b0 - <rustfmt_nightly[2b26fbdfc5662f3a]::Session<std[86a3120b066ce118]::io::stdio::Stdout>>::format
  21:     0x55e429df1b35 - rustfmt[e5cca7ecbdfbf507]::format_and_emit_report::<std[86a3120b066ce118]::io::stdio::Stdout>
  22:     0x55e429e00be9 - <rustfmt_nightly[2b26fbdfc5662f3a]::Session<std[86a3120b066ce118]::io::stdio::Stdout>>::override_config::<rustfmt[e5cca7ecbdfbf507]::format::{closure#0}, ()>
  23:     0x55e429df0895 - rustfmt[e5cca7ecbdfbf507]::execute
  24:     0x55e429dee251 - rustfmt[e5cca7ecbdfbf507]::main
  25:     0x55e429e014e3 - std[86a3120b066ce118]::sys_common::backtrace::__rust_begin_short_backtrace::<fn(), ()>
  26:     0x55e429dffd29 - std[86a3120b066ce118]::rt::lang_start::<()>::{closure#0}
  27:     0x7f0f50d4979e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h8fb8db51461160a5
                               at /rustc/3a8a131e9509c478ece1c58fe0ea2d49463d2300/library/core/src/ops/function.rs:287:13
  28:     0x7f0f50d4979e - std::panicking::try::do_call::h8cad0bb136701789
                               at /rustc/3a8a131e9509c478ece1c58fe0ea2d49463d2300/library/std/src/panicking.rs:485:40
  29:     0x7f0f50d4979e - std::panicking::try::h3a59b3d28fab2a12
                               at /rustc/3a8a131e9509c478ece1c58fe0ea2d49463d2300/library/std/src/panicking.rs:449:19
  30:     0x7f0f50d4979e - std::panic::catch_unwind::h257e63b47d64b708
                               at /rustc/3a8a131e9509c478ece1c58fe0ea2d49463d2300/library/std/src/panic.rs:140:14
  31:     0x7f0f50d4979e - std::rt::lang_start_internal::{{closure}}::h6cbe6465a0c54d37
                               at /rustc/3a8a131e9509c478ece1c58fe0ea2d49463d2300/library/std/src/rt.rs:148:48
  32:     0x7f0f50d4979e - std::panicking::try::do_call::h065165cc1f86d7cb
                               at /rustc/3a8a131e9509c478ece1c58fe0ea2d49463d2300/library/std/src/panicking.rs:485:40
  33:     0x7f0f50d4979e - std::panicking::try::h36cd654271848729
                               at /rustc/3a8a131e9509c478ece1c58fe0ea2d49463d2300/library/std/src/panicking.rs:449:19
  34:     0x7f0f50d4979e - std::panic::catch_unwind::h6b02c76e9346c231
                               at /rustc/3a8a131e9509c478ece1c58fe0ea2d49463d2300/library/std/src/panic.rs:140:14
  35:     0x7f0f50d4979e - std::rt::lang_start_internal::h6fbc0eb973b8dfa5
                               at /rustc/3a8a131e9509c478ece1c58fe0ea2d49463d2300/library/std/src/rt.rs:148:20
  36:     0x55e429df28d5 - main
  37:     0x7f0f509c3790 - <unknown>
  38:     0x7f0f509c384a - __libc_start_main
  39:     0x55e429dd5c19 - <unknown>
  40:                0x0 - <unknown>
````

```
rustfmt 1.5.2-nightly (3a8a131 2023-04-02)

```

[code.rs.txt](https://github.com/rust-lang/rustfmt/files/11138109/code.rs.txt)

**Comment by shulaoda** [comment]
Unable to reproduce this issue, it may have been fixed.
